# syntax=docker/dockerfile:1

# A Dockerfile that uses the local clone of lattice-estimator, incorporating
# local changes that have not yet been merged into malb/lattice-estimator at
# HEAD.
FROM sagemath/sagemath:9.5

COPY --chmod=777 . /lattice-estimator
WORKDIR "/lattice-estimator"

RUN sage -pip install -r requirements.txt
CMD ["sage"]
