# A Dockerfile that can be used in isolation
# syntax=docker/dockerfile:1
FROM sagemath/sagemath:9.5

COPY --chmod=777 . /lattice-estimator
WORKDIR "/lattice-estimator"

RUN sage -pip install -r requirements.txt
CMD ["sage"]
