name: PEP8

on: 
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

env:
  JOBS: 2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v2
      - name: PEP8
        run: |
          pip install --upgrade pyproject-flake8
          flake8 estimator/
